// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@2.0.2";

// src/lib/mcp/tools/listar-inscricoes.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@2.0.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.104.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/listar-inscricoes.ts
var listar_inscricoes_default = defineTool({
  name: "listar_inscricoes",
  title: "Listar inscri\xE7\xF5es",
  description: "Lista as inscri\xE7\xF5es do Encontro das Magn\xF3lias, com filtro opcional por status ou por busca em nome/e-mail.",
  inputSchema: {
    status: z.enum(["pendente", "pago", "recusado", "reembolsado", "chargeback"]).optional().describe("Filtra pelo status da inscri\xE7\xE3o."),
    busca: z.string().trim().min(1).optional().describe("Texto para buscar em nome ou e-mail."),
    limite: z.number().int().min(1).max(200).default(50).describe("M\xE1ximo de registros retornados.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, busca, limite }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("inscricoes").select("id, nome, email, celular, status, valor, valor_liquido, criado_em, pago_em").order("criado_em", { ascending: false }).limit(limite ?? 50);
    if (status) query = query.eq("status", status);
    if (busca) query = query.or(`nome.ilike.%${busca}%,email.ilike.%${busca}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { total: data?.length ?? 0, inscricoes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/resumo-inscricoes.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@2.0.2";
var resumo_inscricoes_default = defineTool2({
  name: "resumo_inscricoes",
  title: "Resumo das inscri\xE7\xF5es",
  description: "Retorna totais por status e a receita bruta e l\xEDquida das inscri\xE7\xF5es pagas do Encontro das Magn\xF3lias.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("inscricoes").select("status, valor, valor_liquido");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const porStatus = {};
    let bruto = 0;
    let liquido = 0;
    for (const row of data ?? []) {
      porStatus[row.status] = (porStatus[row.status] ?? 0) + 1;
      if (row.status === "pago") {
        bruto += Number(row.valor ?? 0);
        liquido += Number(row.valor_liquido ?? 0);
      }
    }
    const resumo = {
      total: data?.length ?? 0,
      por_status: porStatus,
      receita_bruta_pagas: Number(bruto.toFixed(2)),
      receita_liquida_pagas: Number(liquido.toFixed(2))
    };
    return {
      content: [{ type: "text", text: JSON.stringify(resumo) }],
      structuredContent: resumo
    };
  }
});

// src/lib/mcp/tools/atualizar-status-inscricao.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@2.0.2";
import { z as z2 } from "npm:zod@^3.25.76";
var atualizar_status_inscricao_default = defineTool3({
  name: "atualizar_status_inscricao",
  title: "Atualizar status da inscri\xE7\xE3o",
  description: "Atualiza o status de pagamento de uma inscri\xE7\xE3o (por id ou e-mail). Ao marcar como paga, registra a data do pagamento.",
  inputSchema: {
    id: z2.string().uuid().optional().describe("Identificador da inscri\xE7\xE3o."),
    email: z2.string().trim().email().optional().describe("E-mail da inscri\xE7\xE3o, quando o id n\xE3o for conhecido."),
    status: z2.enum(["pendente", "pago", "recusado", "reembolsado", "chargeback"]).describe("Novo status da inscri\xE7\xE3o."),
    valor_liquido: z2.number().min(0).optional().describe("Valor l\xEDquido recebido, se diferente do padr\xE3o.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, email, status, valor_liquido }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    if (!id && !email) {
      return { content: [{ type: "text", text: "Informe id ou email." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const patch = { status };
    if (status === "pago") patch.pago_em = (/* @__PURE__ */ new Date()).toISOString();
    if (typeof valor_liquido === "number") patch.valor_liquido = valor_liquido;
    let query = supabase.from("inscricoes").update(patch);
    query = id ? query.eq("id", id) : query.ilike("email", email);
    const { data, error } = await query.select("id, nome, email, status, valor, valor_liquido, pago_em");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data?.length) {
      return { content: [{ type: "text", text: "Nenhuma inscri\xE7\xE3o encontrada." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { atualizadas: data.length, inscricoes: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "vgytoyfmpvocnjghssji";
var mcp_default = defineMcp({
  name: "site-magnolia",
  title: "Site Magnolia",
  version: "0.1.0",
  instructions: "Ferramentas do site do Encontro das Magn\xF3lias. Use `listar_inscricoes` para consultar inscri\xE7\xF5es, `resumo_inscricoes` para totais e receita, e `atualizar_status_inscricao` para confirmar pagamentos.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [listar_inscricoes_default, resumo_inscricoes_default, atualizar_status_inscricao_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@2.0.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
